### PR TITLE
fix: remove '0.0.' prefill

### LINKED ISSUE #1545: Support arbitrary realms and shards
### Problem

The application should support shard and realm numbers that are non zero for all entity IDs.

Example:
0.2.3
1.2.3

### Solution

Validate the tool can support non zero shards and realms for entity IDs. 
- Do not assume 0.0. for entity IDs

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by Sheng-Long**
Signed-off-by: Tim Schmidt <tim@launchbadge.com>

**Description**:
Support arbitrary realms and shards

**Related issue(s)**:

Fixes #1545 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by SvetBorislavov — CHANGES_REQUESTED** [review]
Please fix the linting warnings

File: front-end/src/renderer/pages/Accounts/LinkExistingAccount/LinkExistingAccount.vue [hunk 1]
```diff
@@ -67,6 +67,7 @@ const handleLinkAccount = async () => {
 };
 
 const handleBlur = (e: Event) => {
+  console.log('handle blur');
```
Comment (SvetBorislavov) [inline front-end/src/renderer/pages/Accounts/LinkExistingAccount/LinkExistingAccount.vue:70]: Please remove that log also

**Review by SvetBorislavov — APPROVED** [review]
