### PR TITLE
fix: transactions table pagination is broken

### LINKED ISSUE #1626: There should be 1 page in the "Ready to sign" tab for the group transaction
### Description

Image

### Steps to reproduce

See above

### Additional context

_No response_

### Hedera network

_No response_

### Version

v0.10.2

### Operating system

None

### PR DESCRIPTION
**Pull request by ericleponner**
**Description**:
Changes below:
1) fix pagination in  transaction tables 
2) enable transaction grouping in `History` tab (when organization mode is enabled)

Those changes introduce a new API point in backend: `GET /transaction-nodes`.
Transaction node is a new entity which represents a single row in a transaction table.

More details in `Notes for reviewer` section

**Related issue(s)**:

Fixes #1626

**Notes for reviewer**:
```
N front-end/src/renderer/services/organization/transactionNode.ts
N back-end/apps/api/src/transactions/nodes/transaction-nodes.controller.ts
N back-end/apps/api/src/transactions/nodes/transaction-nodes.service.ts
N back-end/apps/api/src/transactions/nodes/transaction-nodes.util.ts
N back-end/apps/api/src/transactions/dto/transaction-node.dto.ts
U back-end/apps/api/src/transactions/dto/index.ts
U back-end/apps/api/src/transactions/transactions.module.ts
    # New back-end api point GET /transaction-nodes
    # Returns an array of ITransactionNode
    # Main parameter : collection (ie READY_TO_REVIEW, READY_TO_SIGN...)
    # Not paginated : all collection items are returned at once (to be revisited if needed)
    # TransactionNodesService.getTransactionNodes() is mainly a switch on existing routines
    #   - READY_FOR_REVIEW => TransactionsService.getTransactionsToApprove()
    #   - READY_TO_SIGN => TransactionsService.getTransactionsToSign()
    #   - READY_FOR_EXECUTION => TransactionsService.getTransactions(WAITING_FOR_EXECUTION)
    #   - IN_PROGRESS => TransactionsService.getTransactions(WAITING_FOR_SIGNATURES)
    #   - HISTORY => TransactionsService.getHistoryTransactions()


N middle-end/src/ITransactionNode.ts
N back-end/apps/api/src/transactions/dto/ITransactionNode.ts
U front-end/tsconfig.web.json
    # Interface of objects returned by back-end to front-end
    # Should be a single file located in middle-end/src folder
    # NestJS current setup cannot find files in middle-end folder :(
    # Transient workaround : a copy in back-end/apps/api/src
    # These two files should be IDENTICAL !
    # This will be fixed in the future !

N back-end/libs/common/src/enum-array-validation.pipe.ts
N back-end/libs/common/src/enum-array-validation.pipe.spec.ts
    # New validation pipe used by GET /transaction-nodes

N back-end/apps/api/src/transactions/nodes/transaction-nodes.controller.spec.ts
N back-end/apps/api/src/transactions/nodes/transaction-nodes.service.spec.ts
N back-end/apps/api/src/transactions/nodes/transaction-nodes.util.spec.ts
    # Unit tests for GET /transaction-nodes


N front-end/src/renderer/pages/Transactions/components/TransactionNodeTable.vue
N front-end/src/renderer/pages/Transactions/components/TransactionNodeHead.vue
N front-end/src/renderer/pages/Transactions/components/TransactionNodeRow.vue
N front-end/src/renderer/pages/Transactions/components/SignGroupButton.vue
N front-end/src/renderer/pages/Transactions/components/SignSingleButton.vue
    # TransactionNodeTable replaces the following views:
    #   - InProgress, ReadyForExecution, ReadyForReview and ReadyToSign
    #   - History view is still used in personal mode
    # Parameterized with props.collection
    # Displays columns and button actions according the collection
    # Calls GET /transaction-nodes with the right collection

U front-end/src/renderer/pages/Transactions/Transactions.vue
    # Now uses TransactionNodeTable
    # No longer use InProgress, ReadyForExecution, ReadyForReview and ReadyToSign
    # Uses History in personal mode
    # Uses TransactionNodeTable(HISTORY) in organization mode

D front-end/src/renderer/pages/Transactions/components/InProgress.vue
D front-end/src/renderer/pages/Transactions/components/ReadyForExecution.vue
D front-end/src/renderer/pages/Transactions/components/ReadyForReview.vue
D front-end/src/renderer/pages/Transactions/components/ReadyToSign.vue
    # Replaced by TransactionNodeTable

N front-end/src/renderer/components/Filter/v2/StatusFieldV2.vue
N front-end/src/renderer/components/Filter/v2/TransactionTypeFieldV2.vue
N front-end/src/renderer/components/Filter/v2/TransactionsFilterV2.vue
N front-end/src/renderer/components/Filter/v2/MultipleSelectFilterFieldV2.vue
    # Used by TransactionNodeTable when collection == HISTORY
    # Variants of StatusField and TransactionTypeField
    # These are less generic and simplified

U front-end/src/renderer/composables/usePersonalPassword.ts
    # Added getPasswordV2() (variant of getPassword())
    # Used by SignSingleButton and SignGroupButton views

N front-end/src/renderer/composables/useFilterNotifications.ts
    # Encapsulate some notification logic
    # Equivalent to logic dispersed in InProgress, ReadyForExecution, ReadyForReview…
    # Used by TransactionNodeRow for notification display

N front-end/src/renderer/utils/sortTransactionNodes.ts
U front-end/src/renderer/utils/sdk/transactions.ts
    # Utilities used by TransactionNodeTable and associated views

U front-end/src/shared/interfaces/HederaSchema.ts
    # Formatting
```

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: front-end/src/renderer/composables/useFilterNotifications.ts [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+        // User has probably not access to this transaction
+        // => we ignore silently
+      }
+    }
+    filteredNotifications.value = newCandidates;
+  };
+
+  /* Mount */
+  onMounted(() => {
+    watch(
```
Comment (jbair06) [inline front-end/src/renderer/composables/useFilterNotifications.ts]: I believe watch can be out on its own, and doesn't need to be in onMounted. My understanding is both work, but it is more commonly done outside of onMounted.

File: front-end/src/renderer/utils/sortTransactionNodes.ts [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+        result = compareString(n1.validStart, n2.validStart);
+      }
+      break;
+    case TransactionNodeSortField.VALID_START_DATE:
+      result = compareString(n1.validStart, n2.validStart);
+      if (result === 0) {
+        result = compareString(n1.sdkTransactionId, n2.sdkTransactionId);
+      }
+      break;
+    case TransactionNodeSortField.CREATED_AT_DATE: // To be implemented
```
Comment (jbair06) [inline front-end/src/renderer/utils/sortTransactionNodes.ts]: These are fully implemented now, right? Can the comment be removed?
